'use client';

import { Download, FileText, CheckCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface ThreatReportGeneratorProps {
  sessionId?: string | null;
}

const reportData: Record<string, any> = {
  'SES-20240128-001': {
    scamType: 'UPI Fraud',
    tacticUsed: ['Urgency creation', 'Authority impersonation', 'Phishing link'],
    intelligenceExtracted: 5,
    riskLevel: 'Critical',
    status: 'Complete',
  },
  'SES-20240128-002': {
    scamType: 'Bank KYC Scam',
    tacticUsed: ['Fake bank communication', 'Data extraction', 'Account suspension threat'],
    intelligenceExtracted: 4,
    riskLevel: 'Critical',
    status: 'Complete',
  },
  'SES-20240128-003': {
    scamType: 'Phishing Attack',
    tacticUsed: ['Prize claim lure', 'Credential theft', 'Financial data extraction'],
    intelligenceExtracted: 3,
    riskLevel: 'High',
    status: 'In Progress',
  },
  'SES-20240128-004': {
    scamType: 'Job Scam',
    tacticUsed: ['Salary promise', 'Upfront fee demand', 'Identity theft'],
    intelligenceExtracted: 3,
    riskLevel: 'Medium',
    status: 'Complete',
  },
};

export default function ThreatReportGenerator({ sessionId }: ThreatReportGeneratorProps) {
  if (!sessionId || !reportData[sessionId]) {
    return null;
  }

  const report = reportData[sessionId];
  const isComplete = report.status === 'Complete';

  const downloadReport = () => {
    const reportContent = `
SENTINELAI THREAT INCIDENT REPORT
=====================================
Session ID: ${sessionId}
Generated: ${new Date().toLocaleString()}

THREAT DETAILS
--------------
Scam Type: ${report.scamType}
Risk Level: ${report.riskLevel}
Status: ${report.status}

TACTICS USED
------------
${report.tacticUsed.map((t: string) => `• ${t}`).join('\n')}

INTELLIGENCE EXTRACTED
----------------------
Total Indicators: ${report.intelligenceExtracted}
• UPI IDs: 3
• Phone Numbers: 2
• Bank Accounts: 2
• Phishing URLs: 1
• Suspicious Keywords: 5

RISK LEVEL SUMMARY
------------------
Threat Classification: ${report.riskLevel}
Human Impact Risk: High
Financial Risk: Significant
Data Breach Risk: High

RECOMMENDATIONS
----------------
1. Block all extracted indicators immediately
2. Alert relevant financial institutions
3. Continue monitoring for related patterns
4. Cross-reference with known threat networks

Generated by SentinelAI Defense System
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `sentinel-report-${sessionId}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className={`rounded-lg border p-6 backdrop-blur-sm ${isComplete ? 'border-green-500/30 bg-green-500/10' : 'border-yellow-500/30 bg-yellow-500/10'}`}>
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <FileText className={`h-6 w-6 ${isComplete ? 'text-green-400' : 'text-yellow-400'} flex-shrink-0 mt-1`} />
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-foreground">Automatic Threat Report</h3>
            <p className={`text-sm ${isComplete ? 'text-green-300' : 'text-yellow-300'} mt-1`}>
              {isComplete ? 'Report Ready for Download' : 'Report Generation in Progress'}
            </p>
          </div>
        </div>
        {isComplete && <CheckCircle className="h-6 w-6 text-green-400" />}
      </div>

      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <div className="rounded border border-border/50 bg-muted/20 p-3">
          <p className="text-xs font-semibold text-muted-foreground mb-1">Scam Type</p>
          <p className="text-sm font-mono text-foreground">{report.scamType}</p>
        </div>
        <div className="rounded border border-border/50 bg-muted/20 p-3">
          <p className="text-xs font-semibold text-muted-foreground mb-1">Risk Level</p>
          <p className={`text-sm font-mono ${report.riskLevel === 'Critical' ? 'text-red-400' : report.riskLevel === 'High' ? 'text-orange-400' : 'text-yellow-400'}`}>
            {report.riskLevel}
          </p>
        </div>
        <div className="rounded border border-border/50 bg-muted/20 p-3">
          <p className="text-xs font-semibold text-muted-foreground mb-1">Intelligence Extracted</p>
          <p className="text-sm font-mono text-foreground">{report.intelligenceExtracted} categories</p>
        </div>
        <div className="rounded border border-border/50 bg-muted/20 p-3">
          <p className="text-xs font-semibold text-muted-foreground mb-1">Tactics Identified</p>
          <p className="text-sm font-mono text-foreground">{report.tacticUsed.length} methods</p>
        </div>
      </div>

      <div className="mt-4">
        <h4 className="mb-2 text-sm font-semibold text-foreground">Tactics Used</h4>
        <div className="flex flex-wrap gap-2">
          {report.tacticUsed.map((tactic: string, idx: number) => (
            <span key={idx} className="rounded bg-muted/40 px-2 py-1 text-xs text-muted-foreground">
              {tactic}
            </span>
          ))}
        </div>
      </div>

      {isComplete && (
        <Button
          onClick={downloadReport}
          className="mt-4 w-full border-primary/30 text-primary hover:bg-primary/10 bg-transparent"
          variant="outline"
        >
          <Download className="mr-2 h-4 w-4" />
          Download Report
        </Button>
      )}
    </div>
  );
}
